id: opecha:P007914
initial_creation_type: ocr
source_metadata:
  id: bdr:W26028
  title: ཨ་ཁུ་སྟོན་པ།
  volume:
    98997ae560004a86a25e1e897c2a579e:
      image_group_id: I1KG23249
      title: Volume 1 of a khu ston pa/
      volume_number: 1
      total_pages: 110
  author: ''
  volumes:
    fab388fdb37a43c698abf79b65c6cb41:
      image_group_id: I1KG23249
      title: ''
      volume_number: 1
      total_pages: 110
ebook_metadata:
  title: ཨ་ཁུ་སྟོན་པ།
  author: ''
  sku: P007914
  cover: cover.jpg
  layers:
  - pagination
